apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-api
  labels:
    app: synergychat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api # "I am looking for pods with this sticker."
  template:
    metadata:
      labels:
        app: synergychat-api # "When I create a pod, I put this sticker on it."
    spec:
      containers:
      - name: synergychat-api
        image: bootdotdev/synergychat-api:latest
